### ISSUE TITLE
Adding UE4 project files

### ISSUE THREAD

**Issue by ghost** [ZiyaBahceci/ue4-online-lobby#1]
Hi

When I cut paste your content into a new UE 4 project I have errors (missing class reference and class instances re-typed as Object).

Could you please add a sample UE4 project ?

Thanks for your content.

**Comment by vengaunt** [comment]
Hi @ArThoX , sorry for half a year of delay in response, I did not get any notification whatsoever for your message. Do you still want a project regarding this repo?

**Comment by vengaunt** [comment]
> Hi
> 
> When I cut paste your content into a new UE 4 project I have errors (missing class reference and class instances re-typed as Object).
> 
> Could you please add a sample UE4 project ?
> 
> Thanks for your content.

Hi @ArThoX , I'm sorry that I'm a few months late, but as per your request, the repository is now an UE4 project. Its built in version 4.26. Enjoy!

**Comment by pierrecorsini** [comment]
Thanks for the reply, it's quite far in time now ;) you can close.

**Comment by vengaunt** [comment]
You're welcome. I apologize for such a late answer.
